### ISSUE TITLE
Can it using WebKit WebInspector frontend to present the debugging

### ISSUE THREAD

**Issue by willchenhb** [lexandera/Aardwolf#14]
Great pure JS debugging solution!
I'm wondering if you can use Webkit WebInspector frontend to present the debugging? 
I think it is widely accepted by developers.

Thanks

**Comment by lexandera** [comment]
Hi!

No, unfortunately not. In the early days I was considering integrating aardwolf into weinre and its existing web inspector infrastructure, but this turned out to be more work than expected, so it never happened.

A while ago Apple added support for debugging webviews on iOS using the web inspector in Safari, and everyone at the company I work for has already moved to using that, so I'm afraid this makes it even less likely that aardwolf will ever get such functionality (unless someone takes the time to write the required code).

Alex
